[project]
name = "tplatform-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.2",
    "pillow>=12.1.1",
    "python-dotenv>=1.2.1",
]
